name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
#  - pip=20
#  - pytorch=1.7.0
#  - torchvision=0.8.1
#  - numpy=1.22.2
  - pip:
    - albumentations==0.4.3
    - tokenizers==0.11.6
    - pytorch-lightning==1.5
    - opencv-python==4.5.5.64
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - transformers==4.18.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
    - -e .
